import { StrictMode, useCallback, useEffect, useMemo, useRef, useState } from "react";
import { createRoot } from "react-dom/client";
import { ArrowLeft, ArrowRight, BookOpen, Crown, Flame, Gem, Home, Maximize, Sparkles, Star, Trophy, Volume2, VolumeX } from "lucide-react";
import { QUESTION_BANK, type Difficulty, type Question } from "./data/question-bank";
import "./styles.css";

type RosterStudent = { name: string; playCode?: string; className?: string; seatNo?: number | null };
type ScoreRow = { id?: string | number; member_names: string[] | string; class_label?: string; play_code?: string; score: number; gems: number; attempts?: number; created_at?: string };
type Screen = "start" | "difficulty" | "question" | "complete" | "board";
type SupabaseLike = { from: (table: string) => any; rpc: (name: string, args: Record<string, unknown>) => Promise<{ data: unknown; error: unknown }> };
declare const ClassCode: { loadOrPrompt: () => Promise<RosterStudent[]> };
declare const supabaseClient: SupabaseLike;
const MAINLINE = ["普通字音与拼音","多音字","部首、偏旁与结构","形近字与同音字","加减笔画、添部件与字族规律","近义词","反义词","词义辨析与一词多义","量词","词语搭配","情境选词","叠词与词语构成","关联词与连接句子","标点符号","完整句子","扩写句子","比喻句","句式转换","阅读理解：寻找明确信息","阅读理解：原因与结果","阅读理解：事情先后","阅读理解：简单推断"] as const;
const DIFF: Record<Difficulty, { title: string; icon: string; reward: number; note: string; cls: string }> = { basic: { title: "基础挑战", icon: "🌱", reward: 10, note: "线索明显，稳稳拿分、守住连击！", cls: "difficulty-basic" }, advanced: { title: "进阶挑战", icon: "⭐", reward: 20, note: "放进句子思考，每答对2题得1颗宝石。", cls: "difficulty-advanced" }, brave: { title: "勇者挑战", icon: "🔥", reward: 35, note: "相近选项更考眼力，答对马上得宝石！", cls: "difficulty-brave" } };
const STORAGE_KEY = "tahun2-bc-zonghe-progress-v1";
const fisherYates = <T,>(items: T[]) => { const output = [...items]; for (let i = output.length - 1; i > 0; i -= 1) { const j = Math.floor(Math.random() * (i + 1)); [output[i], output[j]] = [output[j], output[i]]; } return output; };
const namesOf = (value: ScoreRow["member_names"]) => Array.isArray(value) ? value : (() => { try { const parsed = JSON.parse(value); return Array.isArray(parsed) ? parsed : [String(value)]; } catch { return [String(value)]; } })();
function Prompt({ text }: { text: string }) { return <>{text.replace(/<br\s*\/?>(?=.)/gi, "\n").split("\n").map((line, i) => <span className="prompt-line" key={`${i}-${line}`}>{line.split(/（[　\s]*）/).map((part, j, all) => <span key={`${j}-${part}`}>{part}{j < all.length - 1 && <span className="blank-frame" aria-label="填空处" />}</span>)}</span>)}</>; }

function App() {
  const params = useMemo(() => new URLSearchParams(location.search), []);
  const boardRequested = params.get("board") === "1";
  const [screen, setScreen] = useState<Screen>(boardRequested ? "board" : "start");
  const [roster, setRoster] = useState<RosterStudent[]>([]); const [rosterReady, setRosterReady] = useState(false); const [selected, setSelected] = useState<string[]>([]); const [guestNames, setGuestNames] = useState(["", "", ""]);
  const [groupId, setGroupId] = useState(""); const [score, setScore] = useState(0); const [gems, setGems] = useState(0); const [combo, setCombo] = useState(0); const [progress, setProgress] = useState(0); const [slot, setSlot] = useState(0); const [advancedWins, setAdvancedWins] = useState(0); const [infinite, setInfinite] = useState(false); const [infiniteScore, setInfiniteScore] = useState(0);
  const [point, setPoint] = useState(MAINLINE[0]); const [question, setQuestion] = useState<Question | null>(null); const [options, setOptions] = useState<Question["options"]>([]); const [attempts, setAttempts] = useState(0); const [wrong, setWrong] = useState<string[]>([]); const [answered, setAnswered] = useState(false); const [feedback, setFeedback] = useState(""); const [earned, setEarned] = useState(0); const [sound, setSound] = useState(true); const [rows, setRows] = useState<ScoreRow[]>([]); const [boardError, setBoardError] = useState(""); const [saveState, setSaveState] = useState<"idle" | "saving" | "saved" | "error">("idle"); const [scoreSubmitted, setScoreSubmitted] = useState(false); const [boardScope, setBoardScope] = useState<"class" | "all">("class");
  const seenIds = useRef<Set<string>>(new Set()); const audio = useRef<AudioContext | null>(null); const submitted = useRef(false); const latestFinal = useRef({ score: 0, gems: 0 });
  const studentKey = (student: RosterStudent, index: number) => `${student.playCode || "unknown"}::${index}`;
  const selectedStudents = useMemo(() => roster.filter((student, index) => selected.includes(studentKey(student, index))), [roster, selected]);
  const activeNames = useMemo(() => (roster.length ? selectedStudents.map((student) => student.name) : guestNames).map((name) => name.trim()).filter(Boolean), [guestNames, roster, selectedStudents]);
  const normalizedNames = useMemo(() => activeNames.map((name) => name.toLocaleLowerCase()), [activeNames]);
  const hasDuplicateNames = new Set(normalizedNames).size !== normalizedNames.length;
  const selectedCodes = new Set(selectedStudents.map((student) => student.playCode).filter(Boolean));
  const canBegin = activeNames.length >= 2 && activeNames.length <= 3 && !hasDuplicateNames && selectedCodes.size <= 1;
  const playCode = selectedStudents[0]?.playCode || ""; const classLabel = selectedStudents[0]?.className || "访客";
  const boardPlayCodes = useMemo(() => playCode ? [playCode] : [...new Set(roster.map((student) => student.playCode).filter((code): code is string => Boolean(code)))], [playCode, roster]);
  const boardClassLabel = useMemo(() => playCode ? classLabel : [...new Set(roster.filter((student) => boardPlayCodes.includes(student.playCode || "")).map((student) => student.className || student.playCode).filter(Boolean))].join("、"), [boardPlayCodes, classLabel, playCode, roster]);
  const playTone = useCallback((kind: "click" | "correct" | "wrong" | "finish") => { if (!sound) return; const AudioCtor = window.AudioContext || (window as typeof window & { webkitAudioContext?: typeof AudioContext }).webkitAudioContext; if (!AudioCtor) return; const context = audio.current || new AudioCtor(); audio.current = context; const notes = kind === "correct" ? [523, 659, 784] : kind === "finish" ? [523, 659, 784, 1047] : kind === "wrong" ? [220, 185] : [440]; notes.forEach((frequency, index) => { const oscillator = context.createOscillator(); const gain = context.createGain(); oscillator.type = kind === "wrong" ? "sine" : "triangle"; oscillator.frequency.value = frequency; gain.gain.setValueAtTime(.0001, context.currentTime + index * .07); gain.gain.exponentialRampToValueAtTime(.06, context.currentTime + index * .07 + .01); gain.gain.exponentialRampToValueAtTime(.0001, context.currentTime + index * .07 + .13); oscillator.connect(gain).connect(context.destination); oscillator.start(context.currentTime + index * .07); oscillator.stop(context.currentTime + index * .07 + .15); }); }, [sound]);
  useEffect(() => { if (typeof ClassCode !== "undefined" && typeof ClassCode.loadOrPrompt === "function") void ClassCode.loadOrPrompt().then((list) => { const clean = list.filter((student) => student.name?.trim()); setRoster(clean); setRosterReady(true); try { const saved = JSON.parse(localStorage.getItem(STORAGE_KEY) || "null") as { names?: string[]; mode?: "class" | "guest"; playCode?: string } | null; if (saved?.mode === "class" && saved.playCode && clean.some((student) => student.playCode === saved.playCode) && saved.names) setSelected(clean.map((student, index) => ({ student, index })).filter(({ student }) => student.playCode === saved.playCode && saved.names?.includes(student.name)).slice(0, 3).map(({ student, index }) => studentKey(student, index))); } catch { /* ignore malformed local state */ } }).catch(() => setRosterReady(true)); else setRosterReady(true); }, []);
  useEffect(() => { try { const saved = JSON.parse(localStorage.getItem(STORAGE_KEY) || "null") as Partial<{ names: string[]; mode: "class" | "guest"; playCode?: string; score: number; gems: number; combo: number; advancedWins: number; progress: number; slot: number; groupId: string; seenIds: string[]; scoreSubmitted: boolean }> | null; if (!saved || (saved.mode !== "guest" && saved.mode !== "class")) return; if (saved.mode === "class" && !rosterReady) return; const modeChanged = (saved.mode === "guest" && roster.length > 0) || (saved.mode === "class" && !roster.some((student) => student.playCode === saved.playCode)); if (modeChanged) { localStorage.removeItem(STORAGE_KEY); setGroupId(""); setScore(0); setGems(0); setCombo(0); setAdvancedWins(0); setProgress(0); setSlot(0); setPoint(MAINLINE[0]); setGuestNames(["", "", ""]); setScoreSubmitted(false); setSaveState("idle"); submitted.current = false; seenIds.current.clear(); if (!boardRequested) setScreen("start"); return; } if (saved.mode === "guest" && Array.isArray(saved.names)) setGuestNames(saved.names.slice(0, 3)); if (typeof saved.score === "number") setScore(saved.score); if (typeof saved.gems === "number") setGems(saved.gems); if (typeof saved.combo === "number") setCombo(saved.combo); if (typeof saved.advancedWins === "number") setAdvancedWins(saved.advancedWins); const savedProgress = typeof saved.progress === "number" ? Math.min(Math.max(saved.progress, 0), 22) : 0; const savedSlot = typeof saved.slot === "number" ? Math.min(Math.max(saved.slot, 0), 21) : 0; const resumeSlot = Math.min(Math.max(savedSlot, Math.min(savedProgress, 21)), 21); setProgress(savedProgress); setSlot(resumeSlot); setPoint(MAINLINE[resumeSlot]); if (typeof saved.groupId === "string") setGroupId(saved.groupId); if (Array.isArray(saved.seenIds)) seenIds.current = new Set(saved.seenIds); if (saved.scoreSubmitted) { submitted.current = true; setScoreSubmitted(true); setSaveState("saved"); } if (!boardRequested) { if (savedProgress >= 22) setScreen("complete"); else if (savedProgress > 0) setScreen("difficulty"); } } catch { localStorage.removeItem(STORAGE_KEY); } }, [boardRequested, roster, rosterReady]);
  useEffect(() => { if (!groupId || infinite) return; localStorage.setItem(STORAGE_KEY, JSON.stringify({ mode: roster.length ? "class" : "guest", playCode: playCode || null, names: activeNames, score, gems, combo, advancedWins, progress, slot, groupId, seenIds: [...seenIds.current], scoreSubmitted })); }, [activeNames, advancedWins, combo, gems, groupId, infinite, playCode, progress, roster.length, score, scoreSubmitted, slot]);
  useEffect(() => { latestFinal.current = { score, gems }; }, [gems, score]);
  const loadBoard = useCallback(async () => { const client = typeof supabaseClient !== "undefined" ? supabaseClient : null; if (!client) { setBoardError("排行榜服务尚未载入。"); return; } try { let query = client.from("tahun2_bc_zonghe_scores").select("id,member_names,class_label,play_code,score,gems,attempts,created_at").order("score", { ascending: false }).limit(100); if (boardScope === "class" && boardPlayCodes.length === 1) query = query.eq("play_code", boardPlayCodes[0]); else if (boardScope === "class" && boardPlayCodes.length > 1) query = query.in("play_code", boardPlayCodes); const { data, error } = await query; if (error) throw error; setRows((data || []) as ScoreRow[]); setBoardError(""); } catch { setBoardError("排行榜暂时无法连接，游戏仍可正常进行。"); } }, [boardPlayCodes, boardScope]);
  useEffect(() => { if (screen !== "board") return; void loadBoard(); const timer = window.setInterval(() => void loadBoard(), 5000); return () => window.clearInterval(timer); }, [loadBoard, screen]);
  const saveFinalScore = useCallback(async () => { if (submitted.current || scoreSubmitted || infinite || progress < 22 || activeNames.length < 2) return; submitted.current = true; setSaveState("saving"); const client = typeof supabaseClient !== "undefined" ? supabaseClient : null; if (!client) { submitted.current = false; setSaveState("error"); return; } const memberKey = activeNames.map((name) => name.trim().toLocaleLowerCase()).sort().join("|"); const finalScore = latestFinal.current.score; const finalGems = latestFinal.current.gems; try { const { error } = await client.rpc("submit_tahun2_bc_zonghe_score", { p_play_code: playCode || null, p_class_label: classLabel, p_member_key: memberKey, p_member_names: activeNames, p_team_size: activeNames.length, p_score: finalScore, p_gems: finalGems }); if (error) throw error; setScoreSubmitted(true); setSaveState("saved"); } catch { submitted.current = false; setSaveState("error"); } }, [activeNames, classLabel, infinite, playCode, progress, scoreSubmitted]);
  useEffect(() => { if (screen === "complete") void saveFinalScore(); }, [saveFinalScore, screen]);
  const begin = () => { if (!canBegin) return; playTone("click"); setGroupId(crypto.randomUUID()); setScore(0); setGems(0); setCombo(0); setAdvancedWins(0); setProgress(0); setSlot(0); setInfinite(false); setInfiniteScore(0); setScoreSubmitted(false); setSaveState("idle"); seenIds.current.clear(); submitted.current = false; setPoint(MAINLINE[0]); setScreen("difficulty"); };
  const choose = (difficulty: Difficulty) => { playTone("click"); const pool = QUESTION_BANK.filter((item) => item.knowledgePoint === point && item.difficulty === difficulty); const unseen = pool.filter((item) => !seenIds.current.has(item.id)); const candidates = unseen.length ? unseen : pool; const picked = candidates[Math.floor(Math.random() * candidates.length)]; if (!picked) return; setQuestion(picked); setOptions(fisherYates(picked.options)); setAttempts(0); setWrong([]); setAnswered(false); setFeedback(""); setEarned(0); setScreen("question"); };
  const answer = (id: string) => { if (!question || answered || wrong.includes(id)) return; const nextAttempt = attempts + 1; setAttempts(nextAttempt); if (id !== question.correctOptionId) { playTone("wrong"); setWrong((current) => [...current, id]); setCombo(0); setFeedback(nextAttempt === 1 ? "再想一想，找找题目里的关键线索！" : "差一点，换一个答案试试看。"); return; } playTone("correct"); const base = DIFF[question.difficulty].reward; const points = nextAttempt === 1 ? base : nextAttempt === 2 ? Math.round(base / 2) : 0; let bonus = 0; if (nextAttempt === 1 && !infinite) { const nextCombo = combo + 1; setCombo(nextCombo); if (nextCombo === 3) bonus = 5; if (nextCombo === 5) bonus = 10; if (nextCombo === 8) bonus = 15; } if (infinite) setInfiniteScore((current) => current + points); else { setScore((current) => current + points + bonus); setProgress(Math.max(progress, slot + 1)); if (nextAttempt === 1 && question.difficulty === "brave") setGems((current) => current + 1); if (nextAttempt === 1 && question.difficulty === "advanced") { const nextWins = advancedWins + 1; setAdvancedWins(nextWins); if (nextWins % 2 === 0) setGems((current) => current + 1); } } seenIds.current.add(question.id); setEarned(points + bonus); setAnswered(true); setFeedback(nextAttempt === 1 ? "第一次就答对，真棒！" : nextAttempt === 2 ? "第二次答对，获得一半积分！" : "终于找到正确答案，可以继续前进了！"); };
  const next = () => { playTone("click"); if (infinite) { setPoint(MAINLINE[Math.floor(Math.random() * MAINLINE.length)]); setScreen("difficulty"); return; } if (slot >= 21) { playTone("finish"); setProgress(22); setScreen("complete"); return; } const nextSlot = slot + 1; setSlot(nextSlot); setPoint(MAINLINE[nextSlot]); setScreen("difficulty"); };
  const reset = () => { if (!window.confirm("要结束这次冒险并清除本机进度吗？已提交的公开成绩会保留。")) return; localStorage.removeItem(STORAGE_KEY); setGroupId(""); setScore(0); setGems(0); setCombo(0); setProgress(0); setSlot(0); setInfinite(false); setInfiniteScore(0); setScoreSubmitted(false); setSaveState("idle"); submitted.current = false; setSelected([]); setGuestNames(["", "", ""]); seenIds.current.clear(); setScreen("start"); };

  if (screen === "board") return <main className="teacher-screen"><div className="teacher-sky" /><header className="teacher-header"><div><p className="eyebrow">公开排行榜</p><h1><Trophy /> 华文勇者公开排行榜</h1></div><div className="teacher-actions"><button className="button" onClick={() => setScreen("start")}><ArrowLeft /> 返回游戏</button><button className="button" onClick={() => document.documentElement.requestFullscreen?.()}><Maximize /> 全屏</button></div></header><div className="board-filters"><button className={`button ${boardScope === "class" ? "selected" : ""}`} disabled={!boardPlayCodes.length} onClick={() => setBoardScope("class")}>本班</button><button className={`button ${boardScope === "all" ? "selected" : ""}`} onClick={() => setBoardScope("all")}>全部</button></div><section className="ranking-board" aria-live="polite"><div className="ranking-head"><span>名次</span><span>组员</span><span>班级</span><span>宝石</span><span>尝试</span><span>积分</span></div>{rows.length ? rows.map((row, index) => <div className={`ranking-row rank-${Math.min(index + 1, 4)}`} key={row.id || `${row.created_at}-${index}`}><span className="rank-number">{index < 3 ? ["🥇", "🥈", "🥉"][index] : index + 1}</span><strong>{namesOf(row.member_names).map((name, i) => <span key={`${name}-${i}`}>{i ? "、" : ""}{name}</span>)}</strong><span>{row.class_label || "—"}</span><span>💎 {row.gems}</span><span>{row.attempts ?? "—"}</span><b>{row.score}</b></div>) : <div className="empty-ranking"><img src="/assets/guide-lingling.png" alt="华文冒险向导" /><div><h2>等待勇者出发</h2><p>{boardError || "学生完成主线后，成绩会在这里出现。"}</p></div></div>}</section><p className="auto-refresh">每5秒自动更新 · {boardScope === "class" && boardPlayCodes.length ? `当前班级 ${boardClassLabel || boardPlayCodes.join("、")}` : "全部班级"}</p></main>;
  return <main className="game-shell"><div className="world-background" aria-hidden="true" />{screen !== "start" && <header className="game-hud"><div className="hud-brand"><BookOpen /><span>华文勇者大冒险</span></div><div className="hud-stats"><span><Star />积分 <b>{score}</b></span><span><Gem />宝石 <b>{gems}</b></span><span><Flame />连击 <b>×{combo}</b></span>{infinite && <span className="practice-score"><Sparkles />练习星 <b>{infiniteScore}</b></span>}</div><div className="hud-actions"><button className="icon-button" aria-label={sound ? "关闭声音" : "打开声音"} onClick={() => setSound((value) => !value)}>{sound ? <Volume2 /> : <VolumeX />}</button><button className="icon-button" aria-label="全屏" onClick={() => document.documentElement.requestFullscreen?.()}><Maximize /></button><button className="icon-button" aria-label="回到首页" onClick={reset}><Home /></button></div></header>}{screen !== "start" && !infinite && <section className="route-progress"><div className="route-title"><span>知识岛路线</span><b>{progress}/22</b></div><div className="native-progress"><span style={{ width: `${(progress / 22) * 100}%` }} /></div></section>}
    {screen === "start" && <section className="start-screen"><div className="title-cloud"><span className="title-kicker">二年级华文复习游戏</span><h1>华文勇者<br /><em>大冒险</em></h1><p>一起走过知识岛，收集星星与宝石！</p></div><img className="guide-character start-guide" src="/assets/guide-lingling.png" alt="拿着魔法书的华文冒险向导" /><div className="start-card"><div className="speech-bubble"><b>小语：</b>{hasDuplicateNames ? "组员姓名不能重复，请换一个名字。" : roster.length ? "请选择同一班级的2–3位组员！" : "请写下2–3位不重复的组员名字，我们就出发！"}</div><div className="name-fields">{roster.length ? [...new Map(roster.map((student, index) => [student.playCode || `guest-${index}`, roster.filter((item) => (item.playCode || `guest-${roster.indexOf(item)}`) === (student.playCode || `guest-${index}`))])).entries()].map(([code, students]) => <fieldset className="roster-group" key={code}><legend>{students[0]?.className || code}</legend>{students.map((student) => { const index = roster.indexOf(student); const key = studentKey(student, index); const locked = Boolean(selectedStudents[0]?.playCode && student.playCode !== selectedStudents[0]?.playCode); return <label key={key}><input aria-label={`选择组员 ${student.name}`} type="checkbox" checked={selected.includes(key)} disabled={locked || (!selected.includes(key) && selected.length >= 3)} onChange={() => setSelected((current) => current.includes(key) ? current.filter((item) => item !== key) : [...current, key])} /><span>{student.name}</span></label>; })}</fieldset>) : guestNames.map((name, index) => <label key={index}><span>{index < 2 ? `组员 ${index + 1}` : "组员 3（选填）"}</span><input aria-label={`组员 ${index + 1}姓名`} value={name} maxLength={18} placeholder="请输入姓名" onChange={(event) => setGuestNames((current) => current.map((item, itemIndex) => itemIndex === index ? event.target.value : item))} /></label>)}</div><button className="button start-button" disabled={!canBegin} onClick={begin}>踏上冒险路线 <ArrowRight /></button><button className="teacher-link" onClick={() => setScreen("board")}><Trophy /> 公开排行榜</button></div></section>}
    {screen === "difficulty" && <section className="play-stage difficulty-stage"><div className="stage-heading"><p>{infinite ? "无限挑战 · 不计入公开排行榜" : `第 ${slot + 1} 站 · ${activeNames.join("、")}`}</p><h1>{point}</h1><span>选择适合你们的挑战</span></div><div className="difficulty-grid">{(Object.keys(DIFF) as Difficulty[]).map((key) => <button className={`difficulty-card ${DIFF[key].cls}`} key={key} onClick={() => choose(key)}><span className="difficulty-icon">{DIFF[key].icon}</span><h2>{DIFF[key].title}</h2><p>{DIFF[key].note}</p><strong><Star /> 第一次答对 +{DIFF[key].reward}</strong><small>{key === "advanced" ? "💎 每2题获得1颗" : key === "brave" ? "💎 答对马上获得1颗" : "🔥 适合守住Combo"}</small></button>)}</div></section>}
    {screen === "question" && question && <section className="play-stage question-stage"><div className="question-board"><div className="question-meta"><span>{DIFF[question.difficulty].icon} {DIFF[question.difficulty].title}</span><span>{question.knowledgePoint}</span></div><h1 className="question-prompt"><Prompt text={question.prompt} /></h1><div className="options-grid">{options.map((option, index) => <button key={option.id} className={`answer-option ${wrong.includes(option.id) ? "is-wrong" : ""} ${answered && option.id === question.correctOptionId ? "is-correct" : ""}`} disabled={answered || wrong.includes(option.id)} onClick={() => answer(option.id)}><span>{String.fromCharCode(65 + index)}</span><b>{option.text}</b></button>)}</div>{feedback && <div className={`feedback ${answered ? "feedback-correct" : "feedback-wrong"}`} aria-live="polite"><div>{answered ? "🎉" : "💡"}</div><p><strong>{answered ? `获得 ${earned} 分！` : "再试一次"}</strong><span>{feedback}</span></p>{answered && <button className="button" onClick={next}>继续前进 <ArrowRight /></button>}</div>}</div></section>}
    {screen === "complete" && <section className="completion-stage"><div className="celebration-card"><div className="crown"><Crown /></div><p>主线完成！</p><h1>{activeNames.join("、")}<br />成为华文勇者了！</h1><div className="final-stats"><span><Star />正式积分 <b>{score}</b></span><span><Gem />宝石 <b>{gems}</b></span><span><Trophy />完成 <b>22题</b></span></div><p className="save-status" role="status">{saveState === "saving" ? "正在保存公开成绩…" : saveState === "saved" ? "公开成绩已保存" : saveState === "error" ? "公开成绩保存失败，但游戏结果已保留在本机。" : ""}</p><p className="lock-note">正式成绩只提交一次。无限挑战只练习，不影响公开排行榜。</p><div className="completion-actions"><button className="button infinite-button" onClick={() => { setInfinite(true); setPoint(MAINLINE[Math.floor(Math.random() * MAINLINE.length)]); setScreen("difficulty"); }}><Sparkles />进入无限挑战</button><button className="button" onClick={() => setScreen("board")}><Trophy />查看公开排行榜</button></div></div></section>}
  </main>;
}
createRoot(document.getElementById("root")!).render(<StrictMode><App /></StrictMode>);
